#!/usr/bin/env node
/**
 * Builds the server's .env from the local .env plus production overrides.
 *
 *   node scripts/deploy/make-env.mjs <domain> <db-password> <out-file>
 *
 * - Provider keys (LiveKit, Deepgram, Gemini, Groq, Sarvam, Vobiz, Twilio, WhatsApp, Sheets)
 *   are copied from the local .env.
 * - Server-only secrets (AUTH_SECRET, ingest secret, encryption key) are generated once and
 *   kept in .deploy/secrets.json (git-ignored) so redeploys don't log everyone out.
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const [domain, dbPassword, outFile] = process.argv.slice(2);
if (!domain || !dbPassword || !outFile) {
  console.error("usage: make-env.mjs <domain> <db-password> <out-file>");
  process.exit(1);
}

// fileURLToPath, not URL#pathname: the project path contains a space ("MODEL CRM").
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

function parseEnv(file) {
  const out = {};
  if (!fs.existsSync(file)) return out;
  for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    let v = m[2];
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    else v = v.replace(/\s+#.*$/, "");
    out[m[1]] = v;
  }
  return out;
}

const local = parseEnv(path.join(root, ".env"));

const secretsFile = path.join(root, ".deploy", "secrets.json");
fs.mkdirSync(path.dirname(secretsFile), { recursive: true, mode: 0o700 });
const secrets = fs.existsSync(secretsFile) ? JSON.parse(fs.readFileSync(secretsFile, "utf8")) : {};
const ensure = (k, gen) => (secrets[k] ??= gen());
ensure("AUTH_SECRET", () => crypto.randomBytes(32).toString("base64"));
ensure("AGENT_INGEST_SECRET", () => crypto.randomBytes(32).toString("hex"));
ensure("INTEGRATION_ENCRYPTION_KEY", () => crypto.randomBytes(32).toString("base64"));
ensure("CRON_SECRET", () => crypto.randomBytes(24).toString("hex"));
fs.writeFileSync(secretsFile, JSON.stringify(secrets, null, 2), { mode: 0o600 });

const dbUrl = `postgresql://autoneural:${dbPassword}@localhost:5432/autoneural_crm?schema=public`;
const overrides = {
  NODE_ENV: "production",
  APP_URL: `https://${domain}`,
  DATABASE_URL: dbUrl,
  DIRECT_URL: dbUrl,
  REDIS_URL: "redis://localhost:6379",
  AUTH_SECRET: secrets.AUTH_SECRET,
  AUTH_TRUST_HOST: "true",
  AUTH_REQUIRED: "true",
  // Real sends (Twilio WhatsApp, AI calls) — demo *data* is seeded, but nothing is simulated.
  DEMO_MODE: "false",
  // The app's own sign-in protects the site; no extra Basic-Auth wall.
  BASIC_AUTH_USER: "",
  BASIC_AUTH_PASSWORD: "",
  CRON_SECRET: secrets.CRON_SECRET,
  INTEGRATION_ENCRYPTION_KEY: secrets.INTEGRATION_ENCRYPTION_KEY,
  // The server's voice agent must NOT share a name with any other worker (e.g. a laptop),
  // or LiveKit would hand demo calls to a machine logging into a different database.
  AGENT_NAME: `rapidx-${domain.split(".")[0]}-riya`,
  AGENT_INGEST_SECRET: secrets.AGENT_INGEST_SECRET,
  CRM_URL: "http://127.0.0.1:3000",
  AGENT_HEALTH_PORT: "8082",
  GOOGLE_SERVICE_ACCOUNT_JSON: "./service-account.json",
};

// EXTRA_OVERRIDES (JSON) lets a target replace anything above, e.g. a managed database
// URL or AGENT_EXTERNAL for hosts that cannot run the voice agent.
const extra = process.env.EXTRA_OVERRIDES ? JSON.parse(process.env.EXTRA_OVERRIDES) : {};
const merged = { ...local, ...overrides, ...extra };
// Single quotes: both Next.js (dotenv-expand) and python-dotenv leave '$' untouched inside
// them, so passwords/tokens containing '$' are written verbatim.
const quote = (v) => {
  const s = String(v);
  if (!s.includes("'")) return `'${s}'`;
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;
};
const body =
  `# Generated by scripts/deploy/make-env.mjs for ${domain} — do not edit on the server;\n` +
  `# change the local .env (or the overrides in make-env.mjs) and redeploy.\n` +
  Object.entries(merged)
    .map(([k, v]) => `${k}=${quote(v)}`)
    .join("\n") +
  "\n";
fs.writeFileSync(outFile, body, { mode: 0o600 });
console.log(`wrote ${Object.keys(merged).length} variables for ${domain}`);
